[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install uv",
    "uv pip install --system -r requirements.txt"
]

[start]
cmd = "python run_oracle.py"