[phases.setup]
# Force Python 3.11 and include Rust for building tiktoken/pydantic-core
nixPkgs = ["python311", "python311Packages.pip", "gcc", "rustc", "cargo"]

[phases.install]
# Ensure we use Python 3.11's pip
cmds = [
    "python --version",
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt"
]

[start]
cmd = "python -m uvicorn run_oracle:app --host 0.0.0.0 --port ${PORT:-8000}"

[variables]
# Force Python 3.11
NIXPACKS_PYTHON_VERSION = "3.11"