[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'gcc', 'curl']

[phases.install]
cmds = ['chmod +x railway-build.sh', './railway-build.sh']

[start]
cmd = "uvicorn run_oracle:app --host 0.0.0.0 --port $PORT"