[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'gcc', 'curl', 'bash']

[phases.install]
cmds = ['bash .nixpacks/install.sh']

[start]
cmd = "python -m uvicorn run_oracle:app --host 0.0.0.0 --port ${PORT:-8000}"